<a href="https://colab.research.google.com/github/shivashree2121-gif/DL/blob/main/project_3_dl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler # Import StandardScaler
from sklearn.utils.class_weight import compute_class_weight # Import compute_class_weight
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
# Removed Tokenizer and pad_sequences as they are not needed for numerical input

In [ ]:
df=pd.read_csv("/content/Food_Delivery_Time_Prediction.csv")
df

,Order_ID,Order_Date,Order_Hour,Day_of_Week,Is_Weekend,Is_Festival,Weather,Pickup_Zone,Dropoff_Zone,Vehicle_Type,...,Order_Items,Restaurant_Load,Preparation_Time_Min,Road_Distance_km,Delivery_Distance_Category,Traffic_Level,Number_of_Signals,Average_Speed_kmph,Delivery_Priority,Time_taken_min
0,ORD000001,2025-10-28,8,Tuesday,0,0,Clear,CBD,Commercial,Scooter,...,1,Medium,23,30.55,Long,Moderate,15,28.7,Normal,91
1,ORD000002,2025-09-26,12,Friday,0,0,Rain,CBD,CBD,Scooter,...,3,Medium,11,2.25,Short,Moderate,17,23.3,Normal,21
2,ORD000003,2025-01-26,18,Sunday,1,0,Clear,Residential,Residential,Scooter,...,1,Low,31,10.15,Long,Moderate,8,28.9,Normal,52
3,ORD000004,2025-11-19,12,Wednesday,0,0,Cloudy,Residential,Industrial,Bike,...,3,Medium,19,26.33,Long,Low,9,41.4,Normal,59
4,ORD000005,2025-08-04,18,Monday,0,0,Rain,Industrial,Residential,Bike,...,1,Medium,7,30.48,Long,Moderate,8,31.7,Normal,75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,ORD049996,2025-03-08,14,Saturday,1,0,Fog,Industrial,Industrial,Electric Scooter,...,1,Medium,25,33.67,Long,Low,4,28.6,Normal,94
49996,ORD049997,2025-10-23,8,Thursday,0,0,Clear,Suburban,Residential,Bike,...,4,Medium,35,15.92,Long,Low,5,44.0,Normal,54
49997,ORD049998,2025-10-24,7,Friday,0,0,Storm,Residential,CBD,Scooter,...,1,Low,9,19.38,Long,Low,9,23.7,Normal,66
49998,ORD049999,2025-03-16,20,Sunday,1,0,Clear,Residential,CBD,Scooter,...,2,Medium,26,30.92,Long,Moderate,7,28.4,Priority,92
49999,ORD050000,2025-10-21,21,Tuesday,0,0,Rain,Residential,Residential,Bike,...,3,Low,24,35.51,Long,Moderate,8,29.5,Normal,103

In [ ]:
df.head()

,Order_ID,Order_Date,Order_Hour,Day_of_Week,Is_Weekend,Is_Festival,Weather,Pickup_Zone,Dropoff_Zone,Vehicle_Type,...,Order_Items,Restaurant_Load,Preparation_Time_Min,Road_Distance_km,Delivery_Distance_Category,Traffic_Level,Number_of_Signals,Average_Speed_kmph,Delivery_Priority,Time_taken_min
0,ORD000001,2025-10-28,8,Tuesday,0,0,Clear,CBD,Commercial,Scooter,...,1,Medium,23,30.55,Long,Moderate,15,28.7,Normal,91
1,ORD000002,2025-09-26,12,Friday,0,0,Rain,CBD,CBD,Scooter,...,3,Medium,11,2.25,Short,Moderate,17,23.3,Normal,21
2,ORD000003,2025-01-26,18,Sunday,1,0,Clear,Residential,Residential,Scooter,...,1,Low,31,10.15,Long,Moderate,8,28.9,Normal,52
3,ORD000004,2025-11-19,12,Wednesday,0,0,Cloudy,Residential,Industrial,Bike,...,3,Medium,19,26.33,Long,Low,9,41.4,Normal,59
4,ORD000005,2025-08-04,18,Monday,0,0,Rain,Industrial,Residential,Bike,...,1,Medium,7,30.48,Long,Moderate,8,31.7,Normal,75

In [ ]:
df.tail()

,Order_ID,Order_Date,Order_Hour,Day_of_Week,Is_Weekend,Is_Festival,Weather,Pickup_Zone,Dropoff_Zone,Vehicle_Type,...,Order_Items,Restaurant_Load,Preparation_Time_Min,Road_Distance_km,Delivery_Distance_Category,Traffic_Level,Number_of_Signals,Average_Speed_kmph,Delivery_Priority,Time_taken_min
49995,ORD049996,2025-03-08,14,Saturday,1,0,Fog,Industrial,Industrial,Electric Scooter,...,1,Medium,25,33.67,Long,Low,4,28.6,Normal,94
49996,ORD049997,2025-10-23,8,Thursday,0,0,Clear,Suburban,Residential,Bike,...,4,Medium,35,15.92,Long,Low,5,44.0,Normal,54
49997,ORD049998,2025-10-24,7,Friday,0,0,Storm,Residential,CBD,Scooter,...,1,Low,9,19.38,Long,Low,9,23.7,Normal,66
49998,ORD049999,2025-03-16,20,Sunday,1,0,Clear,Residential,CBD,Scooter,...,2,Medium,26,30.92,Long,Moderate,7,28.4,Priority,92
49999,ORD050000,2025-10-21,21,Tuesday,0,0,Rain,Residential,Residential,Bike,...,3,Low,24,35.51,Long,Moderate,8,29.5,Normal,103

In [ ]:
df.describe()

,Order_Hour,Is_Weekend,Is_Festival,Rider_Experience_Years,Rider_Rating,Restaurant_Rating,Order_Items,Preparation_Time_Min,Road_Distance_km,Number_of_Signals,Average_Speed_kmph,Time_taken_min
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000
mean,13.847700,0.283600,0.049100,4.439744,3.951646,4.175368,2.652740,24.03118,26.201744,9.728920,31.759634,83.868980
std,5.525291,0.450749,0.216079,2.927752,0.294960,0.356201,1.590359,8.34877,12.620079,4.330849,9.510842,35.426899
min,0.000000,0.000000,0.000000,0.100000,3.200000,3.300000,1.000000,5.00000,0.080000,2.000000,8.000000,10.000000
25%,10.000000,0.000000,0.000000,2.200000,3.700000,3.900000,1.000000,18.00000,16.330000,6.000000,25.300000,58.000000
50%,14.000000,0.000000,0.000000,3.800000,3.900000,4.200000,2.000000,24.00000,25.620000,9.000000,33.100000,78.000000
75%,19.000000,1.000000,0.000000,5.900000,4.100000,4.400000,4.000000,30.00000,35.480000,14.000000,39.600000,102.000000
max,23.000000,1.000000,1.000000,15.000000,5.000000,5.000000,7.000000,51.00000,70.820000,18.000000,48.300000,180.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Order_ID                    50000 non-null  object
 1   Order_Date                  50000 non-null  object
 2   Order_Hour                  50000 non-null  int64
 3   Day_of_Week                 50000 non-null  object
 4   Is_Weekend                  50000 non-null  int64
 5   Is_Festival                 50000 non-null  int64
 6   Weather                     50000 non-null  object
 7   Pickup_Zone                 50000 non-null  object
 8   Dropoff_Zone                50000 non-null  object
 9   Vehicle_Type                50000 non-null  object
 10  Rider_Experience_Years      50000 non-null  float64
 11  Rider_Rating                50000 non-null  float64
 12  Restaurant_Rating           50000 non-null  float64
 13  Cuisine_Type                50000 non-null  object
 14  Order_Items                 50000 non-null  int64
 15  Restaurant_Load             50000 non-null  object
 16  Preparation_Time_Min        50000 non-null  int64
 17  Road_Distance_km            50000 non-null  float64
 18  Delivery_Distance_Category  50000 non-null  object
 19  Traffic_Level               50000 non-null  object
 20  Number_of_Signals           50000 non-null  int64
 21  Average_Speed_kmph          50000 non-null  float64
 22  Delivery_Priority           50000 non-null  object
 23  Time_taken_min              50000 non-null  int64
dtypes: float64(5), int64(7), object(12)
memory usage: 9.2+ MB

In [ ]:
df.isnull().sum()

Order_ID                      0
Order_Date                    0
Order_Hour                    0
Day_of_Week                   0
Is_Weekend                    0
Is_Festival                   0
Weather                       0
Pickup_Zone                   0
Dropoff_Zone                  0
Vehicle_Type                  0
Rider_Experience_Years        0
Rider_Rating                  0
Restaurant_Rating             0
Cuisine_Type                  0
Order_Items                   0
Restaurant_Load               0
Preparation_Time_Min          0
Road_Distance_km              0
Delivery_Distance_Category    0
Traffic_Level                 0
Number_of_Signals             0
Average_Speed_kmph            0
Delivery_Priority             0
Time_taken_min                0
dtype: int64

In [ ]:
df.shape

(50000, 24)

In [ ]:
df.columns

Index(['Order_ID', 'Order_Date', 'Order_Hour', 'Day_of_Week', 'Is_Weekend',
       'Is_Festival', 'Weather', 'Pickup_Zone', 'Dropoff_Zone', 'Vehicle_Type',
       'Rider_Experience_Years', 'Rider_Rating', 'Restaurant_Rating',
       'Cuisine_Type', 'Order_Items', 'Restaurant_Load',
       'Preparation_Time_Min', 'Road_Distance_km',
       'Delivery_Distance_Category', 'Traffic_Level', 'Number_of_Signals',
       'Average_Speed_kmph', 'Delivery_Priority', 'Time_taken_min'],
      dtype='object')

In [ ]:
print(df['Delivery_Distance_Category'].value_counts())

Delivery_Distance_Category
Long      47238
Medium     2235
Short       527
Name: count, dtype: int64

In [ ]:
X=df['Time_taken_min']
y=df['Delivery_Distance_Category']

In [ ]:
y=y.map({"Short":1,"Long":0})

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=35)

In [ ]:
# Removed tokenizer, as 'Time_taken_min' is a numerical feature.

In [ ]:
# Removed text_to_sequences, as 'Time_taken_min' is a numerical feature.

In [ ]:
from tensorflow.keras.optimizers import Adam

model=Sequential()
# Added input_shape=(1,) for the first Dense layer to correctly handle the single numerical input feature
model.add(Dense(32, activation="relu", input_shape=(1,)))
model.add(Dense(16,activation="relu"))
model.add(Dense(1,activation="sigmoid"))
# Use a lower learning rate for Adam optimizer
model.compile(optimizer=Adam(learning_rate=0.0001),loss="binary_crossentropy",metrics=["accuracy"]) # Combined model compilation here

In [ ]:
# Model compilation moved to the model definition cell for robustness.

In [ ]:
model.summary()

Model: "sequential_18"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_54 (Dense)                │ (None, 32)             │            64 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_55 (Dense)                │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_56 (Dense)                │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 609 (2.38 KB)

 Trainable params: 609 (2.38 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
history=model.fit(X_train_scaled,y_train,epochs=10,batch_size=32,validation_split=0.2, class_weight=class_weights_dict)

Epoch 1/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8447 - loss: 0.2526 - val_accuracy: 0.8515 - val_loss: 0.2966
Epoch 2/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8506 - loss: 0.2496 - val_accuracy: 0.8619 - val_loss: 0.2830
Epoch 3/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8558 - loss: 0.2484 - val_accuracy: 0.8619 - val_loss: 0.2836
Epoch 4/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8586 - loss: 0.2472 - val_accuracy: 0.8515 - val_loss: 0.3140
Epoch 5/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8585 - loss: 0.2467 - val_accuracy: 0.8515 - val_loss: 0.3155
Epoch 6/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8560 - loss: 0.2464 - val_accuracy: 0.8515 - val_loss: 0.3026
Epoch 7/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8582 - loss: 0.2455 - val_accuracy: 0.8515 - val_loss: 0.3063
Epoch 8/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8551 - loss: 0.2452 - val_accuracy: 0.8619 - val_loss: 0.2789
Epoch 9/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8582 - loss: 0.2452 - val_accuracy: 0.8515 - val_loss: 0.3003
Epoch 10/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8539 - loss: 0.2449 - val_accuracy: 0.8619 - val_loss: 0.2816

In [ ]:
loss,accuracy=model.evaluate(X_test_scaled,y_test)
print("Test Loss:",loss)
print("Test Accuracy:",accuracy)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8562 - loss: 0.2928
Test Loss: 0.2928088903427124
Test Accuracy: 0.8561999797821045

In [ ]:
user_input_time=input("Enter your time: ")
# Convert user input to float, reshape, and then scale for model prediction
user_input_time_reshaped = np.array(float(user_input_time)).reshape(-1, 1)
user_input_scaled = scaler.transform(user_input_time_reshaped)

prediction=model.predict(user_input_scaled)
prob=prediction[0][0]

if prob>=0.5:
  print("Short")
  print("Probability: ",round(prob,2)*100,"%")
else:
  print("Long")
  print("Probability: ",round(1-prob,2)*100,"%")

Enter your time: 21
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step
Short
Probability:  97.0 %